deploy_review:
    stage: deploy
    image: devth/helm
    script:
        - init_helm
        - helm upgrade
          --install
          --set web.name="my-super-app-${CI_COMMIT_REF_SLUG}"
          --wait
          --force
          my-super-app-${CI_COMMIT_REF_SLUG}
          ./helm
    except:
        refs:
            - master

deploy_production:
    stage: deploy
    image: devth/helm
    script:
        - init_helm
        - helm upgrade
          --install
          --set web.name="my-super-app-${CI_COMMIT_REF_SLUG}"
          --wait
          --force
          my-super-app-${CI_COMMIT_REF_SLUG}
          ./helm
    only:
        refs:
            - master

.functions: &functions |
    # Functions
    function init_helm() {
        mkdir -p /etc/deploy
        echo ${GKE_SERVICE_ACCOUNT} | base64 -d > /etc/deploy/sa.json
        gcloud auth activate-service-account --key-file /etc/deploy/sa.json --project=disco-outpost-286710
        gcloud container clusters get-credentials poweredit-gke --zone europe-north1-a --project disco-outpost-286710
        helm init --service-account tiller --wait --upgrade
    }

before_script:
- *functions
